In [3]:
import numpy as np

In [4]:

# Had a little help as always
# https://www.geeksforgeeks.org/dice-throw-problem/

# Here is the table of correct answers for 6 sided dice, to check accuracy
# https://wizardofodds.com/gambling/dice/2/
def find_ways(k,n,x):
    if x<1: return 0
    if n==1: return int(x<=k)#1 if true else 0
    num_ways = 0
    for i in range(1,k+1):
        num_ways += find_ways(k,n-1,x-i)
    return num_ways

In [5]:
find_ways(6,5,14)

540

In [6]:
'''
Dynamic Solution -- translated to numpy
'''
def findWays(k,n,x):
    # The extra row/col make indexing easier, but could be removed (it's not really too bad tho)
    table = np.zeros((n+1,x+1))
    
    if k < x:
        table[1][1:k+1] = 1
    else:
        table[1][1:x+1] = 1
    
    
    for i in range(2,n+1):
        for j in range(2,x+1):
            l = 1
            while l<j and l<=k:
                table[i][j] += table[i-1][j-l]
                l+=1

                
    print(table)
    return table[n][x]

    

In [7]:
findWays(6,1,6)

[[ 0.  0.  0.  0.  0.  0.  0.]
 [ 0.  1.  1.  1.  1.  1.  1.]]


1.0

In [10]:
def get_freq(k,n):
    x = n*k
    table = np.zeros((n+1,x+1))
    
    if k < x:
        table[1][:k+1] = 1
    else:
        table[1][:x+1] = 1
    
    
    for i in range(2,n+1):
        for j in range(2,x+1):
            l = 1
            while l<j and l<=k:
                table[i][j] += table[i-1][j-l]
                l+=1
    # print(table)
    return table[n]

In [37]:
%timeit get_freq(100,100)

1min 36s ± 743 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [14]:
def get_list_freq(dice):
    #setup
    #there are n dice, like last time
    n = dice.size
    # x needs to be the upper bound, which would be rolling k on all dice
    x = np.sum(dice)
    # init the table
    table = np.zeros((n+1,x+1))
    
    if np.max(dice) < x:
        table[1][:np.max(dice)+1] = 1
    else:
        table[1][:x+1] = 1
    
    i = 1
    for k in dice:
        # we need to handle each dice face independently
        #might need temporary bound for 2nd loop
        for j in range(2,x+1):
            l = 1
            while l<j and l <=k:
                table[i][j] += table[i-1][j-l]
                l+=1   
        i += 1
    # print(table)
    return table[n]

In [15]:
print(get_list_freq(np.array([6,6,6])))
print(get_freq(6,3))

[  0.   0.   0.   1.   3.   6.  10.  15.  21.  25.  27.  27.  25.  21.  15.
  10.   6.   3.   1.]
[  0.   0.   0.   1.   3.   6.  10.  15.  21.  25.  27.  27.  25.  21.  15.
  10.   6.   3.   1.]


In [33]:
def get_dict_freq(some_dict):
    lis = []
    for key in some_dict:
        lis += [key]*some_dict[key]
    to_call = np.asarray(lis)
    # print(to_call)
    return get_list_freq(to_call)

In [35]:
test = {6:2, 4:1}
print(get_dict_freq(test))
print(get_list_freq(np.array([6,6,4])))

[  0.   0.   0.   1.   3.   6.  10.  14.  18.  20.  20.  18.  14.  10.   6.
   3.   1.]
[  0.   0.   0.   1.   3.   6.  10.  14.  18.  20.  20.  18.  14.  10.   6.
   3.   1.]


In [44]:
np.random.choice(5000,200,replace=False)

array([3946, 4932, 3300, 2189, 3183, 4760,  916,  718, 3598, 1519, 4153,
        516, 3910, 3856, 2764,   14, 4014, 2863, 4911, 3782,  383, 1111,
       4745,  228, 3885, 1166, 2098, 2820,  715, 2777, 4355, 3160, 4642,
       1189,  487, 3315,   91, 4565, 1256, 2324, 1899, 1713, 1788, 4906,
       2708, 4245,  478, 3628, 2427, 1885, 4580, 4675, 1300, 1325, 4424,
       1266, 4961, 2550, 3431, 4790, 3829,   65,  502, 1205, 3390,  307,
       1140, 2047, 1568, 3228, 1144,  409, 2689, 3572, 1578,  289, 3059,
       4816, 4333, 4876, 3595,  714, 3741,  490,  679,  551, 1601,  408,
       2567,   86, 1067, 4306, 2868, 3394, 1661,  915,  829, 1376, 2450,
        227, 3788, 4526, 4532, 1015, 1397, 1942,  191, 4871, 4314, 2538,
        390, 1138, 4668, 1484, 2254, 1065, 1194, 3704, 4626, 3982, 3187,
       1432, 3918,  610, 2564, 3932, 3939, 4929, 1069, 3447, 4058, 3715,
        404,  348, 4045, 3098,  539,  507, 3738,  272,  952, 1619, 2515,
       2420, 2907, 2666, 2362, 2596, 1580,  945, 36