In [79]:
import numpy as np

In [80]:

# Had a little help as always
# https://www.geeksforgeeks.org/dice-throw-problem/

# Here is the table of correct answers for 6 sided dice, to check accuracy
# https://wizardofodds.com/gambling/dice/2/
def find_ways(k,n,x):
    if x<1: return 0
    if n==1: return int(x<=k)#1 if true else 0
    num_ways = 0
    for i in range(1,k+1):
        num_ways += find_ways(k,n-1,x-i)
    return num_ways

In [81]:
find_ways(6,5,14)

540

In [82]:
'''
Dynamic Solution -- translated to numpy
'''
def findWays(k,n,x):
    # The extra row/col make indexing easier, but could be removed (it's not really too bad tho)
    table = np.zeros((n+1,x+1), dtype=np.uint64)
    
    if k < x:
        table[1][1:k+1] = 1
    else:
        table[1][1:x+1] = 1
    
    
    for i in range(2,n+1):
        for j in range(2,x+1):
            l = 1
            while l<j and l<=k:
                table[i][j] += table[i-1][j-l]
                l+=1

                
    print(table)
    return table[n][x]

    

In [83]:
findWays(6,1,6)

[[0 0 0 0 0 0 0]
 [0 1 1 1 1 1 1]]


1

In [84]:
def get_freq(k,n):
    x = n*k
    table = np.zeros((n+1,x+1), dtype = np.uint64)
    
    if k < x:
        table[1][:k+1] = 1
    else:
        table[1][:x+1] = 1
    
    
    for i in range(2,n+1):
        for j in range(2,x+1):
            #table[i][j] = table[i][j-1] + table[i-1][j-1]
            l = 1
            while l<j and l<=k:
                table[i][j] += table[i-1][j-l]
                l+=1
    # print(table)
    return table[n]

In [85]:
get_freq(6,10)

array([      0,       0,       0,       0,       0,       0,       0,
             0,       0,       0,       1,      10,      55,     220,
           715,    2002,    4995,   11340,   23760,   46420,   85228,
        147940,  243925,  383470,  576565,  831204, 1151370, 1535040,
       1972630, 2446300, 2930455, 3393610, 3801535, 4121260, 4325310,
       4395456, 4325310, 4121260, 3801535, 3393610, 2930455, 2446300,
       1972630, 1535040, 1151370,  831204,  576565,  383470,  243925,
        147940,   85228,   46420,   23760,   11340,    4995,    2002,
           715,     220,      55,      10,       1], dtype=uint64)

In [86]:
def get_list_freq(dice):
    #setup
    #there are n dice, like last time
    n = dice.size
    # x needs to be the upper bound, which would be rolling k on all dice
    x = np.sum(dice)
    # init the table
    table = np.zeros((n+1,x+1), dtype=np.uint64)
    
    if np.max(dice) < x:
        table[1][:np.max(dice)+1] = 1
    else:
        table[1][:x+1] = 1
    
    i = 1
    for k in dice:
        # we need to handle each dice face independently
        #might need temporary bound for 2nd loop
        for j in range(2,x+1):
            l = 1
            while l<j and l <=k:
                table[i][j] += table[i-1][j-l]
                l+=1   
        i += 1
#    print(table)
    return table[n]

In [87]:
print(get_list_freq(np.array([6,6,6,4,4,2,10,9])))
print(get_freq(6,3))

[    0     0     0     0     0     0     0     0     1     8    35   112
   292   656  1314  2400  4062  6447  9682 13853 18983 25012 31783 39038
 46428 53538 59924 65158 68873 70801 70801 68873 65158 59924 53538 46428
 39038 31783 25012 18983 13853  9682  6447  4062  2400  1314   656   292]
[ 0  0  0  1  3  6 10 15 21 25 27 27 25 21 15 10  6  3  1]


In [88]:
def get_dict_freq(some_dict):
    lis = []
    for key in some_dict:
        lis += [key]*some_dict[key]
    to_call = np.asarray(lis)
    # print(to_call)
    return get_list_freq(to_call)

In [89]:
test = {6:2, 4:1}
print(get_dict_freq(test))
print(get_list_freq(np.array([6,6,4])))

[ 0  0  0  1  3  6 10 14 18 20 20 18 14 10  6  3  1]
[ 0  0  0  1  3  6 10 14 18 20 20 18 14 10  6  3  1]


In [90]:
np.random.choice(5000,200,replace=False)

array([3399, 2117, 3140,   61,  290, 1394, 1737, 2589, 2838, 3065, 3150,
       3927,  272, 3069, 4754, 3125, 2160, 3071, 4059, 4932, 4973, 4934,
       1710, 4602, 1186,  625, 1235, 3512, 1694, 1082, 2733, 2232, 4921,
       4720, 3256, 4668, 4839, 3820, 1081, 2137, 2255,  443,  645, 3133,
        819,  362, 2309, 2113, 2135,  973, 2763, 3169, 4369, 2963, 1460,
       1208,  322, 2724, 3530, 3054, 4194, 1290,  192,  434, 3479,  526,
       1623, 2881, 4623, 4167,  947,  932, 3703, 3372, 4126, 1153, 1075,
       2475,  363, 2749, 3418,  689, 2863, 2056, 2688, 1863,  846, 1299,
        437, 3971, 3705, 1151,  579, 4828, 4490, 3852, 3134,  146,  423,
        413, 1877, 3407, 4661, 1866,  909, 1699, 3235,   12,  591, 3147,
       2483, 1695, 4114, 3086, 2632, 4058,  262, 3934, 1495, 2039, 3446,
       1977, 2920, 3715, 2564, 3350,  195,  741, 4563, 1258, 2017, 4349,
       1262, 4682, 2008, 1127,  429, 1110, 2201, 4135, 2520,  904, 4533,
       1925, 4710,  774, 1193, 3582, 3973, 3678,   