In [1]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [40]:
'''
Problem 12)
Grab a big 2d array, and assume it represents a function `f(x,y)`
Create functions that compute, for each `(x,y)` in the domain of `f`:
(1) The partial derivatives with respect to `x`, `y`
(2) The four second-order partial derivatives
(3) The gradient vector
(4) The Hessian
'''


# Setting up a bunch of arrays to play around with

A = plt.imread("Sponge.jpg")
#R,G,B,P are all 'big' 2d arrays
R,G,B,P = A[:,:,0],A[:,:,1],A[:,:,2],A[:,:,3]

def f(x,y):
    return x**2 + y**3 +2*x*y

F = np.fromfunction(f,(10,10))


In [41]:
'''
In the case of image processing derivates cannot be calculated from functions, as RGB are not functions.
Instead, compare neighboring indecies to get the rate of change at each location. What needs to be done, as far as I know,
is average the change from the left and right side. If I were building a function for this, say I only needed partials of x,
I would most likely use np.diff, which automatically subtracts neighboring values.

In this case, I wasn't sure if you wanted the (probably most efficient) built in numpy solution, or if you
wanted me to write the method for conceptual understanding. I could do either I believe, so just let me know.
'''
grad= np.gradient(F)

In [42]:
'''
The partial derivative w.r.t. x should be =2x, all indecies except for the first and last of each row
match this exactly.
'''
grad[0]

array([[  1.,   3.,   5.,   7.,   9.,  11.,  13.,  15.,  17.,  19.],
       [  2.,   4.,   6.,   8.,  10.,  12.,  14.,  16.,  18.,  20.],
       [  4.,   6.,   8.,  10.,  12.,  14.,  16.,  18.,  20.,  22.],
       [  6.,   8.,  10.,  12.,  14.,  16.,  18.,  20.,  22.,  24.],
       [  8.,  10.,  12.,  14.,  16.,  18.,  20.,  22.,  24.,  26.],
       [ 10.,  12.,  14.,  16.,  18.,  20.,  22.,  24.,  26.,  28.],
       [ 12.,  14.,  16.,  18.,  20.,  22.,  24.,  26.,  28.,  30.],
       [ 14.,  16.,  18.,  20.,  22.,  24.,  26.,  28.,  30.,  32.],
       [ 16.,  18.,  20.,  22.,  24.,  26.,  28.,  30.,  32.,  34.],
       [ 17.,  19.,  21.,  23.,  25.,  27.,  29.,  31.,  33.,  35.]])

In [43]:
'''
Similarly, the derivative w.r.t. y should be =3y^2, and these values match exactly in all but the first and last
positions. The  reason why the first and last positions are wrong is due to the fact that the rate of change is not
averaged with any values lower/higher than it.

The values of y are very close to what I expected.
'''
grad[1]

array([[   1.,    4.,   13.,   28.,   49.,   76.,  109.,  148.,  193.,
         217.],
       [   3.,    6.,   15.,   30.,   51.,   78.,  111.,  150.,  195.,
         219.],
       [   5.,    8.,   17.,   32.,   53.,   80.,  113.,  152.,  197.,
         221.],
       [   7.,   10.,   19.,   34.,   55.,   82.,  115.,  154.,  199.,
         223.],
       [   9.,   12.,   21.,   36.,   57.,   84.,  117.,  156.,  201.,
         225.],
       [  11.,   14.,   23.,   38.,   59.,   86.,  119.,  158.,  203.,
         227.],
       [  13.,   16.,   25.,   40.,   61.,   88.,  121.,  160.,  205.,
         229.],
       [  15.,   18.,   27.,   42.,   63.,   90.,  123.,  162.,  207.,
         231.],
       [  17.,   20.,   29.,   44.,   65.,   92.,  125.,  164.,  209.,
         233.],
       [  19.,   22.,   31.,   46.,   67.,   94.,  127.,  166.,  211.,
         235.]])

In [44]:
'''
To get the second order partials, I will just input the first order partials into np.gradient

For the second partials w.r.t.  x:

sec_part_x = [d/dx^2, d/dxdy]


For the second partials w.r.t. y:

sec_part_y = [d/dydx, d/dy^2]


To access any of the 4 partials, simply index the array at [0,1] as shown above

'''
sec_part_x,sec_part_y = np.gradient(grad[0]),np.gradient(grad[1])

In [45]:
'''
This  makes building the hessian vector extremely simple, unless I'm totally misunderstanding what you want.
'''
hess = np.append(sec_part_x, sec_part_y,axis=0)
print(hess)

[[[  1.    1.    1.    1.    1.    1.    1.    1.    1.    1. ]
  [  1.5   1.5   1.5   1.5   1.5   1.5   1.5   1.5   1.5   1.5]
  [  2.    2.    2.    2.    2.    2.    2.    2.    2.    2. ]
  [  2.    2.    2.    2.    2.    2.    2.    2.    2.    2. ]
  [  2.    2.    2.    2.    2.    2.    2.    2.    2.    2. ]
  [  2.    2.    2.    2.    2.    2.    2.    2.    2.    2. ]
  [  2.    2.    2.    2.    2.    2.    2.    2.    2.    2. ]
  [  2.    2.    2.    2.    2.    2.    2.    2.    2.    2. ]
  [  1.5   1.5   1.5   1.5   1.5   1.5   1.5   1.5   1.5   1.5]
  [  1.    1.    1.    1.    1.    1.    1.    1.    1.    1. ]]

 [[  2.    2.    2.    2.    2.    2.    2.    2.    2.    2. ]
  [  2.    2.    2.    2.    2.    2.    2.    2.    2.    2. ]
  [  2.    2.    2.    2.    2.    2.    2.    2.    2.    2. ]
  [  2.    2.    2.    2.    2.    2.    2.    2.    2.    2. ]
  [  2.    2.    2.    2.    2.    2.    2.    2.    2.    2. ]
  [  2.    2.    2.    2.    2.    2. 